language: julia
julia:
    - 1.3
    - 1.4
    - nightly

codecov: true
os:
    - linux

matrix:
    allow_failures:
    - julia: nightly
branches:
    only:
        - master

notifications:
    email: false
