name = "DeformableBodies"
uuid = "e53d2b94-6236-11e9-2d7b-535d79ecd3d3"
authors = ["Iago Leal"]
version = "0.0.1"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = ">= 1.1.0"
